import { Blog } from "@/models/Blog";

export const fetchBlogsData = async (): Promise<Blog[]> => {
  return [
    {
      id: "1",
      title: "10 Essential Tips for Writing a Compelling Statement of Purpose",
      excerpt: "Learn how to craft a SOP that stands out and increases your chances of admission.",
      content: "Full blog content here...",
      category: "SOP Writing",
      image: "https://picsum.photos/400/250?random=1",
      author: "Dr. Sarah Johnson",
      publishedAt: "2024-01-15",
      readTime: "8 min read",
      tags: ["SOP", "Writing", "Admission"],
      isBookmarked: false,
    },
    {
      id: "2",
      title: "Student Life in the UK: A Complete Guide for International Students",
      excerpt: "Everything you need to know about living and studying in the United Kingdom.",
      content: "Full blog content here...",
      category: "Student Life",
      image: "https://picsum.photos/400/250?random=2",
      author: "UK Student Ambassador",
      publishedAt: "2024-01-14",
      readTime: "12 min read",
      tags: ["UK", "Student Life", "Guide"],
      isBookmarked: true,
    },
    {
      id: "3",
      title: "How to Choose the Right University: A Step-by-Step Guide",
      excerpt: "Navigate the complex process of selecting the perfect university for your goals.",
      content: "Full blog content here...",
      category: "University Selection",
      image: "https://picsum.photos/400/250?random=3",
      author: "Education Counselor",
      publishedAt: "2024-01-13",
      readTime: "10 min read",
      tags: ["University", "Selection", "Guide"],
      isBookmarked: false,
    },
    {
      id: "4",
      title: "IELTS vs TOEFL: Which Test Should You Take?",
      excerpt: "Compare IELTS and TOEFL to make an informed decision about your English proficiency test.",
      content: "Full blog content here...",
      category: "Test Preparation",
      image: "https://picsum.photos/400/250?random=4",
      author: "Test Prep Expert",
      publishedAt: "2024-01-12",
      readTime: "7 min read",
      tags: ["IELTS", "TOEFL", "Comparison"],
      isBookmarked: false,
    },
    {
      id: "5",
      title: "Managing Finances as an International Student",
      excerpt: "Practical tips for budgeting and managing money while studying abroad.",
      content: "Full blog content here...",
      category: "Finance",
      image: "https://picsum.photos/400/250?random=5",
      author: "Financial Advisor",
      publishedAt: "2024-01-11",
      readTime: "9 min read",
      tags: ["Finance", "Budgeting", "Student"],
      isBookmarked: true,
    },
  ];
};