import { Course } from "@/models/Course";

export const fetchCoursesData = async (): Promise<Course[]> => {
  return [
    {
      id: "1",
      title: "IELTS Preparation Course",
      description: "Complete IELTS preparation with expert guidance",
      category: "IELTS",
      instructor: "Dr. Sarah Johnson",
      students: 2500,
      price: 199,
      rating: 4.8,
      duration: "8 weeks",
      level: "Intermediate",
      image: "https://picsum.photos/300/200?random=1",
      isBookmarked: false,
    },
    {
      id: "2",
      title: "TOEFL Mastery Program",
      description: "Master TOEFL with comprehensive study materials",
      category: "TOEFL",
      instructor: "Prof. Michael Chen",
      students: 1800,
      price: 249,
      rating: 4.7,
      duration: "10 weeks",
      level: "Advanced",
      image: "https://picsum.photos/300/200?random=2",
      isBookmarked: true,
    },
    {
      id: "3",
      title: "University Application Guide",
      description: "Step-by-step guide to university applications",
      category: "Application",
      instructor: "Lisa Rodriguez",
      students: 3200,
      price: 99,
      rating: 4.9,
      duration: "6 weeks",
      level: "Beginner",
      image: "https://picsum.photos/300/200?random=3",
      isBookmarked: false,
    },
    {
      id: "4",
      title: "SOP Writing Workshop",
      description: "Learn to write compelling Statements of Purpose",
      category: "Writing",
      instructor: "Dr. Emily Watson",
      students: 1500,
      price: 149,
      rating: 4.6,
      duration: "4 weeks",
      level: "Intermediate",
      image: "https://picsum.photos/300/200?random=4",
      isBookmarked: false,
    },
    {
      id: "5",
      title: "GRE Quantitative Prep",
      description: "Master GRE quantitative reasoning",
      category: "GRE",
      instructor: "Prof. David Kim",
      students: 2100,
      price: 299,
      rating: 4.8,
      duration: "12 weeks",
      level: "Advanced",
      image: "https://picsum.photos/300/200?random=5",
      isBookmarked: true,
    },
  ];
};
