// src/api/homeApi.ts
import { HomeResponse } from "@/models/Home";
import { Course } from "@/models/Course";
import { News } from "@/models/News";
import { Blog } from "@/models/Blog";

export const fetchHomeData = async (): Promise<HomeResponse> => {
  return {
    user: {
      id: "1",
      name: "John Doe",
      profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    carousel: [
      { id: "1", title: "Personalized Counseling", image: "https://picsum.photos/400/200" },
      { id: "2", title: "Study Abroad", image: "https://picsum.photos/400/201" },
    ],
    courses: [
      {
        id: "1",
        title: "IELTS Preparation Course",
        description: "Complete IELTS preparation with expert guidance",
        category: "IELTS",
        instructor: "Dr. Sarah Johnson",
        students: 2500,
        price: 199,
        rating: 4.8,
        duration: "8 weeks",
        level: "Intermediate",
        image: "https://picsum.photos/300/200?random=1",
        isBookmarked: false,
      },
      {
        id: "2",
        title: "TOEFL Mastery Program",
        description: "Master TOEFL with comprehensive study materials",
        category: "TOEFL",
        instructor: "Prof. Michael Chen",
        students: 1800,
        price: 249,
        rating: 4.7,
        duration: "10 weeks",
        level: "Advanced",
        image: "https://picsum.photos/300/200?random=2",
        isBookmarked: true,
      },
      {
        id: "3",
        title: "University Application Guide",
        description: "Step-by-step guide to university applications",
        category: "Application",
        instructor: "Lisa Rodriguez",
        students: 3200,
        price: 99,
        rating: 4.9,
        duration: "6 weeks",
        level: "Beginner",
        image: "https://picsum.photos/300/200?random=3",
        isBookmarked: false,
      },
    ],
    news: [
      {
        id: "1",
        title: "Top Universities Announce New Admission Policies for 2025",
        excerpt: "Major universities worldwide have updated their admission requirements and policies for the upcoming academic year.",
        content: "Full article content here...",
        category: "University News",
        image: "https://picsum.photos/400/250?random=1",
        author: "Education Reporter",
        publishedAt: "2024-01-15",
        readTime: "5 min read",
        isBookmarked: false,
      },
      {
        id: "2",
        title: "New Visa Processing Times Reduced for International Students",
        excerpt: "Government announces faster visa processing for study abroad applications.",
        content: "Full article content here...",
        category: "Visa Updates",
        image: "https://picsum.photos/400/250?random=2",
        author: "Immigration News",
        publishedAt: "2024-01-14",
        readTime: "3 min read",
        isBookmarked: true,
      },
    ],
    blogs: [
      {
        id: "1",
        title: "10 Essential Tips for Writing a Compelling Statement of Purpose",
        excerpt: "Learn how to craft a SOP that stands out and increases your chances of admission.",
        content: "Full blog content here...",
        category: "SOP Writing",
        image: "https://picsum.photos/400/250?random=1",
        author: "Dr. Sarah Johnson",
        publishedAt: "2024-01-15",
        readTime: "8 min read",
        tags: ["SOP", "Writing", "Admission"],
        isBookmarked: false,
      },
      {
        id: "2",
        title: "Student Life in the UK: A Complete Guide for International Students",
        excerpt: "Everything you need to know about living and studying in the United Kingdom.",
        content: "Full blog content here...",
        category: "Student Life",
        image: "https://picsum.photos/400/250?random=2",
        author: "UK Student Ambassador",
        publishedAt: "2024-01-14",
        readTime: "12 min read",
        tags: ["UK", "Student Life", "Guide"],
        isBookmarked: true,
      },
    ],
  };
};
