import { News } from "@/models/News";

export const fetchNewsData = async (): Promise<News[]> => {
  return [
    {
      id: "1",
      title: "Top Universities Announce New Admission Policies for 2025",
      excerpt: "Major universities worldwide have updated their admission requirements and policies for the upcoming academic year.",
      content: "Full article content here...",
      category: "University News",
      image: "https://picsum.photos/400/250?random=1",
      author: "Education Reporter",
      publishedAt: "2024-01-15",
      readTime: "5 min read",
      isBookmarked: false,
    },
    {
      id: "2",
      title: "New Visa Processing Times Reduced for International Students",
      excerpt: "Government announces faster visa processing for study abroad applications.",
      content: "Full article content here...",
      category: "Visa Updates",
      image: "https://picsum.photos/400/250?random=2",
      author: "Immigration News",
      publishedAt: "2024-01-14",
      readTime: "3 min read",
      isBookmarked: true,
    },
    {
      id: "3",
      title: "Scholarship Opportunities Open for STEM Students",
      excerpt: "Multiple universities offer new scholarship programs for international STEM students.",
      content: "Full article content here...",
      category: "Scholarships",
      image: "https://picsum.photos/400/250?random=3",
      author: "Scholarship Team",
      publishedAt: "2024-01-13",
      readTime: "4 min read",
      isBookmarked: false,
    },
    {
      id: "4",
      title: "Study Abroad Statistics Show Record Growth in 2024",
      excerpt: "Latest data reveals increasing numbers of students choosing to study abroad.",
      content: "Full article content here...",
      category: "Statistics",
      image: "https://picsum.photos/400/250?random=4",
      author: "Research Department",
      publishedAt: "2024-01-12",
      readTime: "6 min read",
      isBookmarked: false,
    },
    {
      id: "5",
      title: "Language Requirements Updated for European Universities",
      excerpt: "European universities revise language proficiency requirements for international applicants.",
      content: "Full article content here...",
      category: "Requirements",
      image: "https://picsum.photos/400/250?random=5",
      author: "European Education",
      publishedAt: "2024-01-11",
      readTime: "4 min read",
      isBookmarked: true,
    },
  ];
};
