export const EApplicationEnvironment = Object.freeze({
    PRODUCTION: 'production',
    DEVELOPMENT: 'development'
});

// activityConstants.js
export const ACTIVITY_TYPES = Object.freeze({
    LOGIN: 'LOGIN',
    LOAN_APPLICATION: 'LOAN_APPLICATION',
    PAYMENT_INITIATED: 'PAYMENT_INITIATED',
    PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    UNIVERSITY_STATUS_UPDATED: 'UNIVERSITY_STATUS_UPDATED',
    QUESTIONNAIRE_SUBMITTED: 'QUESTIONNAIRE_SUBMITTED',
    QUESTIONNAIRE_UPDATED: 'QUESTIONNAIRE_UPDATED'
})

export const ACTIVITY_STATUSES = Object.freeze({
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    SUBMITTED: 'SUBMITTED',
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    UPDATED: 'UPDATED'
})

